### ISSUE TITLE
Document that postcss.config.js works too

### ISSUE THREAD

**Issue by mdaverde** [whoisvadym/eleventy-plugin-postcss#3]
Just tried this locally and it seems to work. Is this config file type officially supported by this plugin?

**Comment by whoisvadym** [comment]
Hi @mdaverde, thanks for showing interest in `eleventy-plugin-postcss`.

You're definitely right, under the hood, this plugin utilizes [postcss-load-config](https://www.npmjs.com/package/postcss-load-config) and works with all config file extensions supported by it.

It would be a good idea to improve readme and highlight this fact. I will put it on my todo list and will address this shortly.

Suggestions and pull requests are very welcome!
